### ISSUE TITLE
Serializing Map

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#35]

**Comment by Polomich** [comment]
Part 4: Map builder
- serialize map
read map from file: 
- 1 concrete builder reads map as saved (used by map editor)
-  1 concrete builder reads map from file and adapt it to a specific level (used during game play every time a new map is entered by the chracter) : Upon creating the map, this concrete builder will adapt
all characters on the map to the level given in input (e.g. the level of the character
entering the map), as well as adapting all items contained in the map.
