### ISSUE TITLE
Serializing Character

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#36]

**Comment by wokidoo** [comment]
**Brainstorm**

To serialize a character, i'll create a static 'SerializeCharacter' class object to handle all save operations. Characters will be saved in csv files with the following data. 

- Fields for character csv
       - name 
       - id
       - ability scores 
       - levels 
       - max HP
       - current HP
       - inventory items (IDs)
       - equipped items (IDs)
