### ISSUE TITLE
Create Campaign Class

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#37]

**Comment by shadowlerone** [comment]
- Make serializable

**Comment by Trim0500** [comment]
- Please provide specs for the class, makes it easier to impl

**Comment by shadowlerone** [comment]
basically:
1. 2D array (or whatever you feel is better) to define where maps are relative to each other.
2. `CampaignMap` -> a `struct` that has the map UUID (or a pointer to a map), the `x` and `y` coordinates of the map within the 2D array
3. Helper functions
  - `get_north(int UUID)`, `get_south(int UUID)`, `get_east(int UUID)`, `get_west(int UUID)` to get neighbouring maps

**Comment by Trim0500** [comment]
---
- A very rough UML for the class

![image](https://github.com/Trim0500/DnD-Character-Creation/assets/70395022/8f83c7d8-4290-4bd7-96d9-639f1e5121b0)
---

**Comment by Trim0500** [comment]
---
- Looking into the specs for the class, we need a unique identifier mechanism for maps too. This can affect how maps are serialized. @Polomich Since you are handling the serialization for a map, this means that you may need to update your work once the id system is in.
- Some tasks that need to be done:
    - Create the campaign class and CampaignMap struct
    - Implement the map id mechanism
    - Serialize the class
---

**Comment by Trim0500** [comment]
---
- Created a task branch for the map IDs: [Task/COMP345-A2-37_--_Implement_Map_IDs](https://github.com/Trim0500/DnD-Character-Creation/tree/Task/COMP345-A2-37_--_Implement_Map_IDs)
---

**Comment by Trim0500** [comment]
---
- Changes for map id have been put in, see [Feat[COMP345-A2-37]: Add in map ids](https://github.com/Trim0500/DnD-Character-Creation/pull/49)
---

**Comment by Trim0500** [comment]
---
- Created a branch for Campaign classes: [Story/COMP345-A2-37_--_Make_Campaign_Class](https://github.com/Trim0500/DnD-Character-Creation/tree/Story/COMP345-A2-37%5D_--_Make_Campaign_Class)
---

**Comment by Trim0500** [comment]
---
- Campaign class created, see [Story/comp345 a2 37 make campaign class](https://github.com/Trim0500/DnD-Character-Creation/pull/50)
---

**Comment by Trim0500** [comment]
---
- Note that the branch for creating serializable functions for the class are in the same branch for making the class
---

**Comment by Trim0500** [comment]
---
- Serialization of the campaign class is done, see [Story/comp345 a2 37 make campaign class](https://github.com/Trim0500/DnD-Character-Creation/pull/51)
---
