### ISSUE TITLE
Create the Game Logger Observer

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#39]

**Comment by shadowlerone** [comment]
Pushed in this commit 11b04c9

Character and Map just need to be made observable now. GUI for observer is underway

**Comment by Trim0500** [comment]
---
- Based on our discord discussion for Assignment 3, the part involving game logger could fall under this issue. Whereby there needs to be a Game and GameLogger class that are the observable and observer respectively.
    - Game is a class that contains the logic as well as the events that are outlined in assignment 3 that when done, notify the logger observable
    - GameLogger is a concrete observer that gets the states of the game to then output events into a log file (txt)

### Assignment 3, Part 4
- Implement a game log using the observer pattern. The log should record game events
from different observables in real-time as they are happening: 1) the game controller
records the events happening in every game phase (game setup, map loading, player
turns switching, end phase) 2) the map records every movement made on the map, 3)
the character records every attack attempted and its result 4) the dice records every
dice roll. All the log entries should be recorded in a unified log. It should be possible to
switch on/off any of the different logging sources.
---
