### ISSUE TITLE
Make Campaigns

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#40]
Good luck ✨

**Comment by Trim0500** [comment]
- Others will need to explain their code to help

**Comment by shadowlerone** [comment]
Yes, though campaigns should be created using the systems developed. This should be last issue tackled.

**Comment by Trim0500** [comment]
---
- A set of pre-generated campaigns are offered at the beginning of the game, from
which the user chooses or lets the computer chose from randomly.
- Characters in a campaign must also be predefined of which the player may choose which to use
---

**Comment by Trim0500** [comment]
---
- With the saving of files now complete, this issue may be started
---
