### ISSUE TITLE
Interactability

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#41]
Take actions:
- Character Movement
- Check container
- (de)quip items

**Comment by Trim0500** [comment]
---
- Movement and targeting should be limited to a certain range. Valid target squares for movement and targeting should be highlighted in order to help the player selecting a target.
---

**Comment by Trim0500** [comment]
---
- It should be noted that equipping/unequipping items are already in place as are taking items and moving them to different containers.
- The ones that are missing right now is moving a character onto a different map cell and attacking. @wokidoo Note that there now exists a method for this action in ``Character`` called ``AttemptAttack`` which only sends an event message so far and can be used to implement an attacking action. There now also exists ``MoveCharacter`` in ``Map`` which similarly only sends an event message right now but can be used to implement a movement action.
---
