### ISSUE TITLE
Character Creation System

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#42]

**Comment by Trim0500** [comment]
- Likely for end of project
- Constructors exist, just need to make it interactable

**Comment by shadowlerone** [comment]
> * Likely for end of project
> 
>     * Constructors exist, just need to make it interactable

correct. for now we just need to have it display the character information, and update when the data in the model changes

**Comment by Trim0500** [comment]
---
### Intermediate
- A user-interactive character editor that allows to create player characters and NPCs. The characters should be stored in a file.

### Final
- A set of pre-generated characters is available at the beginning of the game, from which the user chooses to play the game. The characters can be placed on the map as NPCs (friendly or hostile) during map creation. Characters or NPCs need only to be minimally graphically rendered, i.e. a simple symbol in a map square is sufficient. Animation is not a mandatory requirement.
---

**Comment by Trim0500** [comment]
---
- Moved to #77 
---
