### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#43]
Create issues and link here pls

**Comment by shadowlerone** [comment]
Issues can be references using `#<issueNumber>`, like #45

**Comment by Trim0500** [comment]
---
- Unit Tests for serialization of items and containers are done. See #38
---

**Comment by Trim0500** [comment]
---
- Unit tests and documentation have been done for the Campaign class, see #37 
---
