### ISSUE TITLE
Item serializer bugs

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#54]
Reading item CSVs fails on this file:
[test.csv](https://github.com/Trim0500/DnD-Character-Creation/files/14547808/test.csv)

at line 70. 
![debug info](https://github.com/Trim0500/DnD-Character-Creation/assets/11930788/39f0b543-bad0-41f8-94d1-58aba85681ee)

**Comment by Trim0500** [comment]
See #57
