### ISSUE TITLE
The great GUI Bugfix

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#60]
[My GUI Branch](https://github.com/Trim0500/DnD-Character-Creation/tree/Andrae-GUI) has made a lot of progress.
If you have time, please play around with it and document strange behaviour here.

**Comment by Trim0500** [comment]
---
- Pressing cancel when loading/saving files breaks the program
    - Run the program
    - Click on open/save as
    - Click cancel on the prompt
---

**Comment by Trim0500** [comment]
---
- Can't add in characters to maps
    - Should also need to be able to use IDs on the cells for items and characters

- Scroll always hides the map out of view

- Width and height is misleading for maps
    - Expecting width to be columns and height to be rows (run by height)

- Items' enchantment bonus dropdown selection should be restricted based on item type
    - ![image](https://github.com/Trim0500/DnD-Character-Creation/assets/70395022/e6d13ec3-1777-4c51-aacb-b13defa92c38)
---

**Comment by shadowlerone** [comment]
> Items' enchantment bonus dropdown selection should be restricted based on item type

Add a restriction in `item` class to prevent invalid enchantments. also provide a means to get what would be a valid enchantment for a given item within the item class.

> Scroll always hides the map out of view

low priority
