### ISSUE TITLE
Reset IDs at Run-time and Set IDs Based on Loaded Components

### ISSUE THREAD

**Issue by Trim0500** [Trim0500/DnD-Character-Creation#75]
---
### Description
- Everytime we run the program, test cases make it so that when we use the GUI window to make more instances of Maps, Items & Characters, the IDs are quite large and may not be 100% consistent. There needs to be some code in place to reset the IDs after tests and set the IDs when loading these components.
---

**Comment by Trim0500** [comment]
---
- While the resetting of the IDs after tests have been put in place, I'm not sure how to handle the setting of the ID generators for the serialized objects. Will need help on this.
---

**Comment by shadowlerone** [comment]
idea: IDs only need to be unique within Campaigns, right?

So we have two mechanisms: one for when you're loading items already associated with a campaign and one for when you're importing an external item file.

# Items already associated with a campaign

These items should already have unique IDs, and they should be sequential. When the items file is loaded, the items are simply added to a vector. 

# Items from outside the campaign

When the file is loaded, the items' IDs are ignored. They are added to the end of the vector, and their new IDs are their indices.
