### ISSUE TITLE
Create Doors for Linking Maps

### ISSUE THREAD

**Issue by Trim0500** [Trim0500/DnD-Character-Creation#78]
---
### Description
- using a door in one map leads the character to the entry door of another map
---

**Comment by Trim0500** [comment]
---
- Not too sure which deliverable to label the issue with and whom to assign. Will need to follow up.
---

**Comment by shadowlerone** [comment]
pseudocode, in a hypothetical game class
```c++
Game::warp(int map_id, int x, int y){
    load_map(map_id); // updates current map
    current_map->setCell(x,y, player_character); // place the player on the destination cell
}
```

**Comment by Trim0500** [comment]
---
- Note that there now in fact exists the ``Game`` class which contains the ``LoadMap`` method that right now only sends an event but can be used to implement the functionality outlined in this issue
---
